name: Build and Deploy Code

on: push

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: 13012004
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 13012004
          POSTGRES_DB: fastapi_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: pulling get repo
        uses: actions/checkout@v3

      - name: installing python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: updating pip
        run: python -m pip install --upgrade pip

      - name: installing all dependencies
        run: pip install -r requirements.txt

      - name: running test with pytest
        run: |
          pip install pytest
          pytest




