name: Build and Deploy Code

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: pulling get repo
      uses: actions/checkout@v3
    - name: install python version 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
      - name: updating pip
        run: python -m pip install --upgrade pip
      - name: installing all dependencies
        run: pip install -r requirements.txt




